import pandas as pd
from src.decorators import log_execution, time_execution

class TimeSeriesFeatureEngineer:
    """
    Class to perform feature engineering on time series data.
    Methods include extracting datetime features, calculating rolling statistics,
    and creating lag/lead features.
    """

    def __init__(self,df:pd.DataFrame):
        self.df = df
    
    @log_execution
    def extract_datetime_features(self):
        """Extracts various datetime features from the DataFrame index."""
        if self.df is not None and isinstance(self.df.index,pd.DatetimeIndex):
            self.df['year'] = self.df.index.year
            self.df['month'] = self.sf.index.month
            self.df['day'] = self.df.index.day
            self.df['hour'] = self.df.index.hour
            self.df['dayofweek'] = self.df.index.dayofweek
            self.df['dayofyear'] = self.df.index.dayofyear
            self.df['quarter'] = self.df.index.quarter
            self.df['weekofyear'] = self.df.index.isocalendar().week
        else:
            raise ValueError("DataFrame index must be a DatetimeIndex and not None.")
        return self.df
    
    @log_execution
    def create_rolling_stats(self,column,window,stats=['mean','std']):
        """Creates rolling window statistics for a specified column."""
        if self.df is not None and column in self.df.columns:
            for stat in stats:
                if stat =="mean":
                    self.df[f'rolling_mean_{window}'] = self.df[column].rolling(window=window).mean()
                elif stat == "std":
                    self.df[f'rolling_std_{window}'] = self.df[column].rolling(window=window).std()
                elif stat == "min":
                    self.df[f'rolling_min_{window}'] = self.df[column].rolling(window=window).min()
                elif stat == "max":
                    self.df[f'rolling_min_{window}'] = self.df[column].rolling(window=window).max()
                else:
                    raise ValueError("Unsupported rolling stats. ")
        else:
            raise ValueError(f"Column '{column} not found in DataFrame.")
        return self.df    


    @log_execution
    def create_lag_features(self,column,lags):
        """Creates ag features for the specified column."""
        if self.df is not None and column in self.df.columns:
            for lag in lags:
                self.df[f'lag_{lag}'] = self.df[column].shift(lag)
        else:
            raise ValueError(f"Column '{column}' not found in DataFrame.")
        return self.df

    @log_execution
    def create_lead_features(self,column,leads):
        """Creates lead features for the specified column."""
        if self.df is not None and column in self.df.columns:
            for lead in leads:
                self.df[f'lead_{lead}']=self.df[column].shift(-lead)
        else:
            raise ValueError(f"Column '{column}' not found in DataFrame.")
        return self.df

    @log_execution
    def drop_na(self):
        """Drops rows with NaN values generated by feature engineering."""
        self.df.dropna(inplace=True)
        return self.df


